version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend-python
      - backend-rails

  backend-python:
    build:
      context: ./backend-python
    ports:
      - "8000:8000"
    volumes:
      - ./backend-python/app:/app
    depends_on:
      - backend-rails

  backend-rails:
    build:
      context: ./backend-rails
    ports:
      - "3001:3001"
    volumes:
      - ./backend-rails:/app
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/chatapp_development

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatapp_development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: